### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by stub1t** [dirkjanm/adidnsdump#18]
I needed to install the future package to be able to run it:
`python3 -m pip install future`

```
Traceback (most recent call last):
  File "/home/user/.local/bin/adidnsdump", line 5, in <module>
    from adidnsdump import main
  File "/home/user/.local/lib/python3.11/site-packages/adidnsdump/__init__.py", line 1, in <module>
    from adidnsdump.dnsdump import main
  File "/home/user/.local/lib/python3.11/site-packages/adidnsdump/dnsdump.py", line 43, in <module>
    from future.utils import itervalues, iteritems, native_str
ModuleNotFoundError: No module named 'future'
```

**Comment by CipherCloak** [comment]
pip3 install future

**Comment by dirkjanm** [comment]
the future requirement is now dropped, making the codebase python3 only
