### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ghost** [dirkjanm/adidnsdump#2]
```
[-] Connecting to host...
[-] Binding to host
[+] Bind OK
[-] Querying zone for records
[+] Found nnnnn records
Traceback (most recent call last):
  File "/usr/local/bin/adidnsdump", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/adidnsdump/dnsdump.py", line 445, in main
    outfile.write('{type},{name},{ip}\n'.format(**row))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 12: ordinal not in range(128) 
```

**Comment by dirkjanm** [comment]
Think I fixed it now :p

![image](https://user-images.githubusercontent.com/1773762/56826547-cdc48880-685c-11e9-86e4-46d17f68b3aa.png)
