### ISSUE TITLE
dns.name.EmptyLabel: A DNS label is empty.

### ISSUE THREAD

**Issue by okiwoki** [dirkjanm/adidnsdump#5]
When running adidnsdump, sometimes the following error occurs:

Traceback (most recent call last):
  File "/usr/local/bin/adidnsdump", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/adidnsdump/dnsdump.py", line 422, in main
    res = dnsresolver.query('%s.%s.' % (recordname, zone), 'A', tcp=args.dns_tcp)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 848, in query
    qname = dns.name.from_text(qname, None)
  File "/usr/lib/python2.7/dist-packages/dns/name.py", line 889, in from_text
    return from_unicode(text, origin, idna_codec)
  File "/usr/lib/python2.7/dist-packages/dns/name.py", line 852, in from_unicode
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

This happens when using the following command and switches:
adidnsdump -u DOMAIN\\USER -p PASSWORD -r -v FQDN.DC.COM

Is there anything I need to do on my end to help fix this?

**Comment by dirkjanm** [comment]
Not sure what causes this but it should at least not crash anymore now
