### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by youngd24** [dirkjanm/adidnsdump#6]
Python 2.7.5
impacket pulled today

Get the following: 

[-] Connecting to host...
[-] Binding to host
[+] Bind OK
[-] Querying zone for records
Traceback (most recent call last):
  File "/bin/adidnsdump", line 9, in <module>
    load_entry_point('adidnsdump==1.1.0', 'console_scripts', 'adidnsdump')()
  File "build/bdist.linux-x86_64/egg/adidnsdump/dnsdump.py", line 443, in main
  File "build/bdist.linux-x86_64/egg/impacket/structure.py", line 84, in __init__
  File "build/bdist.linux-x86_64/egg/impacket/structure.py", line 142, in fromString
  File "build/bdist.linux-x86_64/egg/impacket/structure.py", line 535, in calcUnpackSize
TypeError: Struct() argument 1 must be string, not unicode

**Comment by dirkjanm** [comment]
Sorry I can't reproduce this, and this doesn't contain enough information to do anything useful with it.
