### ISSUE TITLE
NameErr: DSID-03100238, problem 2001 (NO_OBJECT)

### ISSUE THREAD

**Issue by qgrosperrin** [dirkjanm/adidnsdump#8]
Using latest version from HEAD.
Was trying to dump records from target network. Was able to use `--print-zones` successfully.
Tried different domain controllers both over SSL and without, with same output

```
[-] Connecting to host...
[-] Binding to host
[+] Bind OK
[-] Querying zone for records
Traceback (most recent call last):
  File "/usr/local/bin/adidnsdump", line 11, in <module>
    load_entry_point('adidnsdump==1.2.0', 'console_scripts', 'adidnsdump')()
  File "/usr/local/lib/python2.7/dist-packages/adidnsdump/dnsdump.py", line 420, in main
    c.extend.standard.paged_search(searchtarget, sfilter, search_scope=LEVEL, attributes=['dnsRecord','dNSTombstoned','name'], paged_size=500, generator=False)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/__init__.py", line 125, in paged_search
    paged_criticality)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/PagedSearch.py", line 121, in paged_search_accumulator
    paged_criticality):
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/PagedSearch.py", line 84, in paged_search_generator
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - CN=MicrosoftDNS,DC=DomainDnsZones,DC=eur,DC=sub,DC=clientdomain,DC=com - 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
        'CN=MicrosoftDNS,DC=DomainDnsZones,DC=eur,DC=sub,DC=clientdomain,DC=com'
 - searchResDone - None
```

The tool is running through proxychains.

**Comment by InTheFog-DT** [comment]
Same issue, also run through proxychains

**Comment by dirkjanm** [comment]
Is it listed as a "Forest DNS Zone"? In that case you would need to add the `--forest` parameter, otherwise you will get this error. Similar for legacy zones which require the `--legacy` flag.

**Comment by InTheFog-DT** [comment]
Worked, thank you @dirkjanm!

**Comment by qgrosperrin** [comment]
Indeed, thanks a lot !
