### ISSUE TITLE
ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password

### ISSUE THREAD

**Issue by IPv777** [dirkjanm/adidnsdump#9]
Hello,
I always get the error `ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password` when I'm trying to enumerate on our DNS zone.

```[94m[-][0m Connecting to host...
[94m[-][0m Binding to host
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\adidnsdump.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\adidnsdump\dnsdump.py", line 375, in main
    if not c.bind():
  File "c:\python38\lib\site-packages\ldap3\core\connection.py", line 607, in bind
    raise LDAPUnknownAuthenticationMethodError(self.last_error)
ldap3.core.exceptions.LDAPUnknownAuthenticationMethodError: NTLM needs domain\username and a password
```

but I'm correctly specifying the DOMAIN\\\\user and the password...

Thanks :)

**Comment by IPv777** [comment]
EDIT : it's working from WSL so the problem should come from Windows environment...

**Comment by dirkjanm** [comment]
I think Windows doesn't need the double \

**Comment by IPv777** [comment]
> 
> 
> I think Windows doesn't need the double \

You're right, thanks :D It was that !

**Comment by IPv777** [comment]
#10
